# Generated by Django 5.0.6 on 2024-05-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expiry_date',
            new_name='exp_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='manufact_date',
            new_name='manuf_date',
        ),
    ]
