# Generated by Django 5.0.6 on 2024-05-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_expiry_date_product_exp_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manuf_date',
            new_name='mf_date',
        ),
    ]
